name: fuels
description: Dart FFI bridge to Fuel Rust SDK
version: 1.9.0
homepage: https://github.com/Fuelet/fuels-dart/tree/main/packages/fuels

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  ffi: 2.0.1
  flutter_rust_bridge: 1.74.0
  uuid: 3.0.7 # must be compatible with flutter_rust_bridge version
  freezed_annotation: 2.2.0
  meta: 1.8.0
  collection: 1.16.0

dev_dependencies:
  test: ^1.24.2
  lints: ^2.0.0
  ffigen: 7.2.4
  freezed: ^2.3.2
  build_runner: ^2.3.2
