name: Publish flutter_fuels package release

on:
  push:
    tags:
      - "flutter_fuels@*"

jobs:
  publish_github_release:
    if: ${{ contains(github.event.head_commit.message, '- flutter_fuels@') }}
    # macOS because we can cross-compile to all other platforms from it
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Extract flutter_fuels package version
        # Extracts the 'flutter_fuels' package version from the commit message
        # Stores it into an environment variable
        run: |
          echo "FLUTTER_FUELS_VERSION=$(\
            echo "${{ github.event.head_commit.message }}" | awk '/- flutter_fuels@/ {print ENV_VAR=$2}'\
          )" >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v2
      - uses: goto-bus-stop/setup-zig@v2
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - name: Build all library binaries
        run: melos run build

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{env.FLUTTER_FUELS_VERSION}}
          files: platform-build/*

  publish_pub_dev_release:
    needs: publish_github_release
    uses: ./.github/workflows/publish-pub-dev-release.yml
