name: Publish flutter_fuels package release

on:
  push:
    tags:
      - "flutter_fuels-*"

jobs:
  publish_github_release:
    uses: ./.github/workflows/publish-github-release.yml

  publish_pub_dev_release:
    needs: publish_github_release
    uses: ./.github/workflows/publish-pub-dev-release.yml
    with:
      package_name: flutter_fuels
